name: build

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'russian-cv.tex'
      - 'README.md'
      - '.github/workflows/build-russian.yaml'

jobs:
    build_latex:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - name: Set up Git repository
          uses: actions/checkout@v4
#        - name: Compile LaTeX document
#          uses: xu-cheng/latex-action@v3
#          with:
#            root_file: cv.tex
#        - name: Upload PDF file
#          uses: actions/upload-artifact@v4
#          id: artifact-upload-step
#          with:
#            name: PDF
#            path: cv.pdf

        - uses: actions/setup-python@v5
          with:
            python-version: 3.13
        - uses: abatilo/actions-poetry@v3
          with:
            poetry-version: "latest"

        - name: Install dependencies
          run: | 
            cd md-transformer
            poetry install --no-root

        - name: Run transformer
          env:
            GEMINI_TOKEN: ${{ secrets.GEMINI_TOKEN }}
          run: |
            cd md-transformer
            poetry run python3 md-transformer.py

        - uses: stefanzweifel/git-auto-commit-action@v5
          with:
            commit_message: Update README