name: build

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'russian-cv.tex'
      - 'README.md'
      - '.github/workflows/build-russian.yaml'

jobs:
    build_latex:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - name: Set up Git repository
          uses: actions/checkout@v4
        - name: Compile LaTeX document
          uses: xu-cheng/latex-action@v3
          with:
            root_file: cv.tex
        - name: Upload PDF file
          uses: actions/upload-artifact@v4
          id: artifact-upload-step
          with:
            name: PDF
            path: cv.pdf
        - name: Update README
          run: |
            echo '### 📄 My Resume\n[Download PDF](${{ steps.artifact-upload-step.outputs.artifact-id }})' > README.md
        - uses: stefanzweifel/git-auto-commit-action@v5
          with:
            commit_message: Update README